// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace RetirementStudio._UIMaps.CostOfLivingAdjustments_UKClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class CostOfLivingAdjustments_UK
    {
        
        #region Properties
        public wRetirementStudio wRetirementStudio
        {
            get
            {
                if ((this.mwRetirementStudio == null))
                {
                    this.mwRetirementStudio = new wRetirementStudio();
                }
                return this.mwRetirementStudio;
            }
        }
        #endregion
        
        #region Fields
        private wRetirementStudio mwRetirementStudio;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wRetirementStudio : WinWindow
    {
        
        public wRetirementStudio()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Retirement Studio";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public wStatutoryCPI wStatutoryCPI
        {
            get
            {
                if ((this.mwStatutoryCPI == null))
                {
                    this.mwStatutoryCPI = new wStatutoryCPI(this);
                }
                return this.mwStatutoryCPI;
            }
        }
        
        public wStatutoryRPI wStatutoryRPI
        {
            get
            {
                if ((this.mwStatutoryRPI == null))
                {
                    this.mwStatutoryRPI = new wStatutoryRPI(this);
                }
                return this.mwStatutoryRPI;
            }
        }
        
        public wRevaluation_DeferredPension wRevaluation_DeferredPension
        {
            get
            {
                if ((this.mwRevaluation_DeferredPension == null))
                {
                    this.mwRevaluation_DeferredPension = new wRevaluation_DeferredPension(this);
                }
                return this.mwRevaluation_DeferredPension;
            }
        }
        
        public wRevaluation_Rate_V wRevaluation_Rate_V
        {
            get
            {
                if ((this.mwRevaluation_Rate_V == null))
                {
                    this.mwRevaluation_Rate_V = new wRevaluation_Rate_V(this);
                }
                return this.mwRevaluation_Rate_V;
            }
        }
        
        public wRevaluation_Rate_P wRevaluation_Rate_P
        {
            get
            {
                if ((this.mwRevaluation_Rate_P == null))
                {
                    this.mwRevaluation_Rate_P = new wRevaluation_Rate_P(this);
                }
                return this.mwRevaluation_Rate_P;
            }
        }
        
        public wRevaluation_Rate_T wRevaluation_Rate_T
        {
            get
            {
                if ((this.mwRevaluation_Rate_T == null))
                {
                    this.mwRevaluation_Rate_T = new wRevaluation_Rate_T(this);
                }
                return this.mwRevaluation_Rate_T;
            }
        }
        
        public wRevaluation_CumulativeMax wRevaluation_CumulativeMax
        {
            get
            {
                if ((this.mwRevaluation_CumulativeMax == null))
                {
                    this.mwRevaluation_CumulativeMax = new wRevaluation_CumulativeMax(this);
                }
                return this.mwRevaluation_CumulativeMax;
            }
        }
        
        public wRevaluation_PensionIncrease wRevaluation_PensionIncrease
        {
            get
            {
                if ((this.mwRevaluation_PensionIncrease == null))
                {
                    this.mwRevaluation_PensionIncrease = new wRevaluation_PensionIncrease(this);
                }
                return this.mwRevaluation_PensionIncrease;
            }
        }
        
        public wIncrease_Starts_YearsFrom wIncrease_Starts_YearsFrom
        {
            get
            {
                if ((this.mwIncrease_Starts_YearsFrom == null))
                {
                    this.mwIncrease_Starts_YearsFrom = new wIncrease_Starts_YearsFrom(this);
                }
                return this.mwIncrease_Starts_YearsFrom;
            }
        }
        
        public wIncrease_Starts_Date_V wIncrease_Starts_Date_V
        {
            get
            {
                if ((this.mwIncrease_Starts_Date_V == null))
                {
                    this.mwIncrease_Starts_Date_V = new wIncrease_Starts_Date_V(this);
                }
                return this.mwIncrease_Starts_Date_V;
            }
        }
        
        public wIncrease_Starts_Date_D wIncrease_Starts_Date_D
        {
            get
            {
                if ((this.mwIncrease_Starts_Date_D == null))
                {
                    this.mwIncrease_Starts_Date_D = new wIncrease_Starts_Date_D(this);
                }
                return this.mwIncrease_Starts_Date_D;
            }
        }
        
        public wIncrease_Ends_YearsFrom wIncrease_Ends_YearsFrom
        {
            get
            {
                if ((this.mwIncrease_Ends_YearsFrom == null))
                {
                    this.mwIncrease_Ends_YearsFrom = new wIncrease_Ends_YearsFrom(this);
                }
                return this.mwIncrease_Ends_YearsFrom;
            }
        }
        
        public wIncrease_Ends_Date_V wIncrease_Ends_Date_V
        {
            get
            {
                if ((this.mwIncrease_Ends_Date_V == null))
                {
                    this.mwIncrease_Ends_Date_V = new wIncrease_Ends_Date_V(this);
                }
                return this.mwIncrease_Ends_Date_V;
            }
        }
        
        public wIncrease_Ends_Date_D wIncrease_Ends_Date_D
        {
            get
            {
                if ((this.mwIncrease_Ends_Date_D == null))
                {
                    this.mwIncrease_Ends_Date_D = new wIncrease_Ends_Date_D(this);
                }
                return this.mwIncrease_Ends_Date_D;
            }
        }
        
        public wIncrease_Amount_Rate_V wIncrease_Amount_Rate_V
        {
            get
            {
                if ((this.mwIncrease_Amount_Rate_V == null))
                {
                    this.mwIncrease_Amount_Rate_V = new wIncrease_Amount_Rate_V(this);
                }
                return this.mwIncrease_Amount_Rate_V;
            }
        }
        
        public wIncrease_Amount_Rate_P wIncrease_Amount_Rate_P
        {
            get
            {
                if ((this.mwIncrease_Amount_Rate_P == null))
                {
                    this.mwIncrease_Amount_Rate_P = new wIncrease_Amount_Rate_P(this);
                }
                return this.mwIncrease_Amount_Rate_P;
            }
        }
        
        public wIncrease_Amount_Rate_T wIncrease_Amount_Rate_T
        {
            get
            {
                if ((this.mwIncrease_Amount_Rate_T == null))
                {
                    this.mwIncrease_Amount_Rate_T = new wIncrease_Amount_Rate_T(this);
                }
                return this.mwIncrease_Amount_Rate_T;
            }
        }
        
        public wIncrease_Pension wIncrease_Pension
        {
            get
            {
                if ((this.mwIncrease_Pension == null))
                {
                    this.mwIncrease_Pension = new wIncrease_Pension(this);
                }
                return this.mwIncrease_Pension;
            }
        }
        
        public wCommon_cbo_V wCommon_cbo_V
        {
            get
            {
                if ((this.mwCommon_cbo_V == null))
                {
                    this.mwCommon_cbo_V = new wCommon_cbo_V(this);
                }
                return this.mwCommon_cbo_V;
            }
        }
        
        public wCommon_txt_P wCommon_txt_P
        {
            get
            {
                if ((this.mwCommon_txt_P == null))
                {
                    this.mwCommon_txt_P = new wCommon_txt_P(this);
                }
                return this.mwCommon_txt_P;
            }
        }
        
        public wCommon_cbo_T wCommon_cbo_T
        {
            get
            {
                if ((this.mwCommon_cbo_T == null))
                {
                    this.mwCommon_cbo_T = new wCommon_cbo_T(this);
                }
                return this.mwCommon_cbo_T;
            }
        }
        
        public wCommon_txt_D wCommon_txt_D
        {
            get
            {
                if ((this.mwCommon_txt_D == null))
                {
                    this.mwCommon_txt_D = new wCommon_txt_D(this);
                }
                return this.mwCommon_txt_D;
            }
        }
        
        public wWholeDPRevaluation wWholeDPRevaluation
        {
            get
            {
                if ((this.mwWholeDPRevaluation == null))
                {
                    this.mwWholeDPRevaluation = new wWholeDPRevaluation(this);
                }
                return this.mwWholeDPRevaluation;
            }
        }
        #endregion
        
        #region Fields
        private wStatutoryCPI mwStatutoryCPI;
        
        private wStatutoryRPI mwStatutoryRPI;
        
        private wRevaluation_DeferredPension mwRevaluation_DeferredPension;
        
        private wRevaluation_Rate_V mwRevaluation_Rate_V;
        
        private wRevaluation_Rate_P mwRevaluation_Rate_P;
        
        private wRevaluation_Rate_T mwRevaluation_Rate_T;
        
        private wRevaluation_CumulativeMax mwRevaluation_CumulativeMax;
        
        private wRevaluation_PensionIncrease mwRevaluation_PensionIncrease;
        
        private wIncrease_Starts_YearsFrom mwIncrease_Starts_YearsFrom;
        
        private wIncrease_Starts_Date_V mwIncrease_Starts_Date_V;
        
        private wIncrease_Starts_Date_D mwIncrease_Starts_Date_D;
        
        private wIncrease_Ends_YearsFrom mwIncrease_Ends_YearsFrom;
        
        private wIncrease_Ends_Date_V mwIncrease_Ends_Date_V;
        
        private wIncrease_Ends_Date_D mwIncrease_Ends_Date_D;
        
        private wIncrease_Amount_Rate_V mwIncrease_Amount_Rate_V;
        
        private wIncrease_Amount_Rate_P mwIncrease_Amount_Rate_P;
        
        private wIncrease_Amount_Rate_T mwIncrease_Amount_Rate_T;
        
        private wIncrease_Pension mwIncrease_Pension;
        
        private wCommon_cbo_V mwCommon_cbo_V;
        
        private wCommon_txt_P mwCommon_txt_P;
        
        private wCommon_cbo_T mwCommon_cbo_T;
        
        private wCommon_txt_D mwCommon_txt_D;
        
        private wWholeDPRevaluation mwWholeDPRevaluation;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wStatutoryCPI : WinWindow
    {
        
        public wStatutoryCPI(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "radStatutoryCPI";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinRadioButton rd
        {
            get
            {
                if ((this.mrd == null))
                {
                    this.mrd = new WinRadioButton(this);
                    #region Search Criteria
                    this.mrd.SearchProperties[WinRadioButton.PropertyNames.Name] = "Statutory CPI";
                    this.mrd.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mrd;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mrd;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wStatutoryRPI : WinWindow
    {
        
        public wStatutoryRPI(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "radStatutoryRPI";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinRadioButton rd
        {
            get
            {
                if ((this.mrd == null))
                {
                    this.mrd = new WinRadioButton(this);
                    #region Search Criteria
                    this.mrd.SearchProperties[WinRadioButton.PropertyNames.Name] = "Statutory RPI";
                    this.mrd.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mrd;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mrd;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wRevaluation_DeferredPension : WinWindow
    {
        
        public wRevaluation_DeferredPension(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "chkDeferredPension";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinCheckBox chk
        {
            get
            {
                if ((this.mchk == null))
                {
                    this.mchk = new WinCheckBox(this);
                    #region Search Criteria
                    this.mchk.SearchProperties[WinCheckBox.PropertyNames.Name] = "Deferred pension at valuation date";
                    this.mchk.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mchk;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mchk;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wRevaluation_Rate_V : WinWindow
    {
        
        public wRevaluation_Rate_V(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_btnVariable";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinButton btn
        {
            get
            {
                if ((this.mbtn == null))
                {
                    this.mbtn = new WinButton(this);
                    #region Search Criteria
                    this.mbtn.SearchProperties[WinButton.PropertyNames.Name] = "V";
                    this.mbtn.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mbtn;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mbtn;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wRevaluation_Rate_P : WinWindow
    {
        
        public wRevaluation_Rate_P(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_btnRate";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinButton btn
        {
            get
            {
                if ((this.mbtn == null))
                {
                    this.mbtn = new WinButton(this);
                    #region Search Criteria
                    this.mbtn.SearchProperties[WinButton.PropertyNames.Name] = "%";
                    this.mbtn.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mbtn;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mbtn;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wRevaluation_Rate_T : WinWindow
    {
        
        public wRevaluation_Rate_T(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_btnTable";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinButton btn
        {
            get
            {
                if ((this.mbtn == null))
                {
                    this.mbtn = new WinButton(this);
                    #region Search Criteria
                    this.mbtn.SearchProperties[WinButton.PropertyNames.Name] = "T";
                    this.mbtn.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mbtn;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mbtn;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wRevaluation_CumulativeMax : WinWindow
    {
        
        public wRevaluation_CumulativeMax(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "rateCumulativeMax";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public txt txt
        {
            get
            {
                if ((this.mtxt == null))
                {
                    this.mtxt = new txt(this);
                }
                return this.mtxt;
            }
        }
        #endregion
        
        #region Fields
        private txt mtxt;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class txt : WinEdit
    {
        
        public txt(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinEdit.PropertyNames.Name] = "Text area";
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinEdit UIRateCumulativeMaxEdit1
        {
            get
            {
                if ((this.mUIRateCumulativeMaxEdit1 == null))
                {
                    this.mUIRateCumulativeMaxEdit1 = new WinEdit(this);
                    #region Search Criteria
                    this.mUIRateCumulativeMaxEdit1.SearchProperties[WinEdit.PropertyNames.Name] = "A single text character";
                    this.mUIRateCumulativeMaxEdit1.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mUIRateCumulativeMaxEdit1;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUIRateCumulativeMaxEdit1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wRevaluation_PensionIncrease : WinWindow
    {
        
        public wRevaluation_PensionIncrease(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboPensionIncreaseLabels";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinComboBox cbo
        {
            get
            {
                if ((this.mcbo == null))
                {
                    this.mcbo = new WinComboBox(this);
                    #region Search Criteria
                    this.mcbo.SearchProperties[WinComboBox.PropertyNames.Name] = "Pension increase label";
                    this.mcbo.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mcbo;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mcbo;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wIncrease_Starts_YearsFrom : WinWindow
    {
        
        public wIncrease_Starts_YearsFrom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboLatestOfYearsFrom";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinComboBox cbo
        {
            get
            {
                if ((this.mcbo == null))
                {
                    this.mcbo = new WinComboBox(this);
                    #region Search Criteria
                    this.mcbo.SearchProperties[WinComboBox.PropertyNames.Name] = "Increases in payment";
                    this.mcbo.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mcbo;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mcbo;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wIncrease_Starts_Date_V : WinWindow
    {
        
        public wIncrease_Starts_Date_V(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_btnVariable";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinButton btn
        {
            get
            {
                if ((this.mbtn == null))
                {
                    this.mbtn = new WinButton(this);
                    #region Search Criteria
                    this.mbtn.SearchProperties[WinButton.PropertyNames.Name] = "V";
                    this.mbtn.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mbtn;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mbtn;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wIncrease_Starts_Date_D : WinWindow
    {
        
        public wIncrease_Starts_Date_D(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_btnDate";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinButton btn
        {
            get
            {
                if ((this.mbtn == null))
                {
                    this.mbtn = new WinButton(this);
                    #region Search Criteria
                    this.mbtn.SearchProperties[WinButton.PropertyNames.Name] = "D";
                    this.mbtn.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mbtn;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mbtn;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wIncrease_Ends_YearsFrom : WinWindow
    {
        
        public wIncrease_Ends_YearsFrom(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboYearsFromColaEnds";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinComboBox cbo
        {
            get
            {
                if ((this.mcbo == null))
                {
                    this.mcbo = new WinComboBox(this);
                    #region Search Criteria
                    this.mcbo.SearchProperties[WinComboBox.PropertyNames.Name] = "Years from";
                    this.mcbo.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mcbo;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mcbo;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wIncrease_Ends_Date_V : WinWindow
    {
        
        public wIncrease_Ends_Date_V(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_btnVariable";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "3";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinButton btn
        {
            get
            {
                if ((this.mbtn == null))
                {
                    this.mbtn = new WinButton(this);
                    #region Search Criteria
                    this.mbtn.SearchProperties[WinButton.PropertyNames.Name] = "V";
                    this.mbtn.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mbtn;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mbtn;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wIncrease_Ends_Date_D : WinWindow
    {
        
        public wIncrease_Ends_Date_D(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_btnDate";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinButton btn
        {
            get
            {
                if ((this.mbtn == null))
                {
                    this.mbtn = new WinButton(this);
                    #region Search Criteria
                    this.mbtn.SearchProperties[WinButton.PropertyNames.Name] = "D";
                    this.mbtn.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mbtn;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mbtn;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wIncrease_Amount_Rate_V : WinWindow
    {
        
        public wIncrease_Amount_Rate_V(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_btnVariable";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "4";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinButton btn
        {
            get
            {
                if ((this.mbtn == null))
                {
                    this.mbtn = new WinButton(this);
                    #region Search Criteria
                    this.mbtn.SearchProperties[WinButton.PropertyNames.Name] = "V";
                    this.mbtn.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mbtn;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mbtn;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wIncrease_Amount_Rate_P : WinWindow
    {
        
        public wIncrease_Amount_Rate_P(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_btnRate";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinButton btn
        {
            get
            {
                if ((this.mbtn == null))
                {
                    this.mbtn = new WinButton(this);
                    #region Search Criteria
                    this.mbtn.SearchProperties[WinButton.PropertyNames.Name] = "%";
                    this.mbtn.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mbtn;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mbtn;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wIncrease_Amount_Rate_T : WinWindow
    {
        
        public wIncrease_Amount_Rate_T(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_btnTable";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinButton btn
        {
            get
            {
                if ((this.mbtn == null))
                {
                    this.mbtn = new WinButton(this);
                    #region Search Criteria
                    this.mbtn.SearchProperties[WinButton.PropertyNames.Name] = "T";
                    this.mbtn.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mbtn;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mbtn;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wIncrease_Pension : WinWindow
    {
        
        public wIncrease_Pension(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboPensionIncreaseLabels2";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinComboBox cbo
        {
            get
            {
                if ((this.mcbo == null))
                {
                    this.mcbo = new WinComboBox(this);
                    #region Search Criteria
                    this.mcbo.SearchProperties[WinComboBox.PropertyNames.Name] = "Pension increase label:";
                    this.mcbo.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mcbo;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mcbo;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wCommon_cbo_V : WinWindow
    {
        
        public wCommon_cbo_V(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_cboVariable";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinComboBox cbo
        {
            get
            {
                if ((this.mcbo == null))
                {
                    this.mcbo = new WinComboBox(this);
                    #region Search Criteria
                    this.mcbo.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mcbo;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mcbo;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wCommon_txt_P : WinWindow
    {
        
        public wCommon_txt_P(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_numEditRate";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public txt1 txt
        {
            get
            {
                if ((this.mtxt == null))
                {
                    this.mtxt = new txt1(this);
                }
                return this.mtxt;
            }
        }
        #endregion
        
        #region Fields
        private txt1 mtxt;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class txt1 : WinEdit
    {
        
        public txt1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinEdit.PropertyNames.Name] = "Text area";
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinEdit UI_numEditRateEdit1
        {
            get
            {
                if ((this.mUI_numEditRateEdit1 == null))
                {
                    this.mUI_numEditRateEdit1 = new WinEdit(this);
                    #region Search Criteria
                    this.mUI_numEditRateEdit1.SearchProperties[WinEdit.PropertyNames.Name] = "A single text character";
                    this.mUI_numEditRateEdit1.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mUI_numEditRateEdit1;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUI_numEditRateEdit1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wCommon_cbo_T : WinWindow
    {
        
        public wCommon_cbo_T(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_cboTableName";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinComboBox cbo
        {
            get
            {
                if ((this.mcbo == null))
                {
                    this.mcbo = new WinComboBox(this);
                    #region Search Criteria
                    this.mcbo.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mcbo;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mcbo;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wCommon_txt_D : WinWindow
    {
        
        public wCommon_txt_D(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_dteEditDate";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public cbo cbo
        {
            get
            {
                if ((this.mcbo == null))
                {
                    this.mcbo = new cbo(this);
                }
                return this.mcbo;
            }
        }
        #endregion
        
        #region Fields
        private cbo mcbo;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class cbo : WinComboBox
    {
        
        public cbo(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinEdit txt
        {
            get
            {
                if ((this.mtxt == null))
                {
                    this.mtxt = new WinEdit(this);
                    #region Search Criteria
                    this.mtxt.SearchProperties[WinEdit.PropertyNames.Name] = "Text area";
                    this.mtxt.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mtxt;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mtxt;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wWholeDPRevaluation : WinWindow
    {
        
        public wWholeDPRevaluation(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "chkWholeDPRevaluation";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinCheckBox chk
        {
            get
            {
                if ((this.mchk == null))
                {
                    this.mchk = new WinCheckBox(this);
                    #region Search Criteria
                    this.mchk.SearchProperties[WinCheckBox.PropertyNames.Name] = "Whole DP Revaluation";
                    this.mchk.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mchk;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mchk;
        #endregion
    }
}
