// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 12.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace RetirementStudio._UIMaps.FAEFormulaClasses
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using System.Drawing;
    using System.Text.RegularExpressions;
    using System.Windows.Input;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WinControls;
    using Microsoft.VisualStudio.TestTools.UnitTesting;
    using Keyboard = Microsoft.VisualStudio.TestTools.UITesting.Keyboard;
    using Mouse = Microsoft.VisualStudio.TestTools.UITesting.Mouse;
    using MouseButtons = System.Windows.Forms.MouseButtons;
    
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public partial class FAEFormula
    {
        
        #region Properties
        public wRetirementStudio wRetirementStudio
        {
            get
            {
                if ((this.mwRetirementStudio == null))
                {
                    this.mwRetirementStudio = new wRetirementStudio();
                }
                return this.mwRetirementStudio;
            }
        }
        #endregion
        
        #region Fields
        private wRetirementStudio mwRetirementStudio;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wRetirementStudio : WinWindow
    {
        
        public wRetirementStudio()
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.Name] = "Retirement Studio";
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public wStandard wStandard
        {
            get
            {
                if ((this.mwStandard == null))
                {
                    this.mwStandard = new wStandard(this);
                }
                return this.mwStandard;
            }
        }
        
        public wCustomCode wCustomCode
        {
            get
            {
                if ((this.mwCustomCode == null))
                {
                    this.mwCustomCode = new wCustomCode(this);
                }
                return this.mwCustomCode;
            }
        }
        
        public wServiceProrateFormula wServiceProrateFormula
        {
            get
            {
                if ((this.mwServiceProrateFormula == null))
                {
                    this.mwServiceProrateFormula = new wServiceProrateFormula(this);
                }
                return this.mwServiceProrateFormula;
            }
        }
        
        public wServiceProrateReduction wServiceProrateReduction
        {
            get
            {
                if ((this.mwServiceProrateReduction == null))
                {
                    this.mwServiceProrateReduction = new wServiceProrateReduction(this);
                }
                return this.mwServiceProrateReduction;
            }
        }
        
        public wPayAverage wPayAverage
        {
            get
            {
                if ((this.mwPayAverage == null))
                {
                    this.mwPayAverage = new wPayAverage(this);
                }
                return this.mwPayAverage;
            }
        }
        
        public wService wService
        {
            get
            {
                if ((this.mwService == null))
                {
                    this.mwService = new wService(this);
                }
                return this.mwService;
            }
        }
        
        public wServiceLimitTo wServiceLimitTo
        {
            get
            {
                if ((this.mwServiceLimitTo == null))
                {
                    this.mwServiceLimitTo = new wServiceLimitTo(this);
                }
                return this.mwServiceLimitTo;
            }
        }
        
        public wStopAccrualAt_C wStopAccrualAt_C
        {
            get
            {
                if ((this.mwStopAccrualAt_C == null))
                {
                    this.mwStopAccrualAt_C = new wStopAccrualAt_C(this);
                }
                return this.mwStopAccrualAt_C;
            }
        }
        
        public wStopAccrualAt_V wStopAccrualAt_V
        {
            get
            {
                if ((this.mwStopAccrualAt_V == null))
                {
                    this.mwStopAccrualAt_V = new wStopAccrualAt_V(this);
                }
                return this.mwStopAccrualAt_V;
            }
        }
        
        public wStopAccrualAt_TXT wStopAccrualAt_TXT
        {
            get
            {
                if ((this.mwStopAccrualAt_TXT == null))
                {
                    this.mwStopAccrualAt_TXT = new wStopAccrualAt_TXT(this);
                }
                return this.mwStopAccrualAt_TXT;
            }
        }
        
        public wStopAccrualAt_cbo wStopAccrualAt_cbo
        {
            get
            {
                if ((this.mwStopAccrualAt_cbo == null))
                {
                    this.mwStopAccrualAt_cbo = new wStopAccrualAt_cbo(this);
                }
                return this.mwStopAccrualAt_cbo;
            }
        }
        
        public wRateTiersBasedOn wRateTiersBasedOn
        {
            get
            {
                if ((this.mwRateTiersBasedOn == null))
                {
                    this.mwRateTiersBasedOn = new wRateTiersBasedOn(this);
                }
                return this.mwRateTiersBasedOn;
            }
        }
        
        public wNumberOfRateTiers wNumberOfRateTiers
        {
            get
            {
                if ((this.mwNumberOfRateTiers == null))
                {
                    this.mwNumberOfRateTiers = new wNumberOfRateTiers(this);
                }
                return this.mwNumberOfRateTiers;
            }
        }
        
        public wIntegrationType wIntegrationType
        {
            get
            {
                if ((this.mwIntegrationType == null))
                {
                    this.mwIntegrationType = new wIntegrationType(this);
                }
                return this.mwIntegrationType;
            }
        }
        
        public wNumberOfBreakPoints wNumberOfBreakPoints
        {
            get
            {
                if ((this.mwNumberOfBreakPoints == null))
                {
                    this.mwNumberOfBreakPoints = new wNumberOfBreakPoints(this);
                }
                return this.mwNumberOfBreakPoints;
            }
        }
        
        public wFPGrid wFPGrid
        {
            get
            {
                if ((this.mwFPGrid == null))
                {
                    this.mwFPGrid = new wFPGrid(this);
                }
                return this.mwFPGrid;
            }
        }
        
        public wCommonTXT_FPGrid wCommonTXT_FPGrid
        {
            get
            {
                if ((this.mwCommonTXT_FPGrid == null))
                {
                    this.mwCommonTXT_FPGrid = new wCommonTXT_FPGrid(this);
                }
                return this.mwCommonTXT_FPGrid;
            }
        }
        
        public wFPGrid_horizontalBar wFPGrid_horizontalBar
        {
            get
            {
                if ((this.mwFPGrid_horizontalBar == null))
                {
                    this.mwFPGrid_horizontalBar = new wFPGrid_horizontalBar(this);
                }
                return this.mwFPGrid_horizontalBar;
            }
        }
        
        public wBreakpoint1_C wBreakpoint1_C
        {
            get
            {
                if ((this.mwBreakpoint1_C == null))
                {
                    this.mwBreakpoint1_C = new wBreakpoint1_C(this);
                }
                return this.mwBreakpoint1_C;
            }
        }
        
        public wBreakpoint1_V wBreakpoint1_V
        {
            get
            {
                if ((this.mwBreakpoint1_V == null))
                {
                    this.mwBreakpoint1_V = new wBreakpoint1_V(this);
                }
                return this.mwBreakpoint1_V;
            }
        }
        
        public wBreakpoint1_TXT wBreakpoint1_TXT
        {
            get
            {
                if ((this.mwBreakpoint1_TXT == null))
                {
                    this.mwBreakpoint1_TXT = new wBreakpoint1_TXT(this);
                }
                return this.mwBreakpoint1_TXT;
            }
        }
        
        public wBreakpoint1_cbo wBreakpoint1_cbo
        {
            get
            {
                if ((this.mwBreakpoint1_cbo == null))
                {
                    this.mwBreakpoint1_cbo = new wBreakpoint1_cbo(this);
                }
                return this.mwBreakpoint1_cbo;
            }
        }
        #endregion
        
        #region Fields
        private wStandard mwStandard;
        
        private wCustomCode mwCustomCode;
        
        private wServiceProrateFormula mwServiceProrateFormula;
        
        private wServiceProrateReduction mwServiceProrateReduction;
        
        private wPayAverage mwPayAverage;
        
        private wService mwService;
        
        private wServiceLimitTo mwServiceLimitTo;
        
        private wStopAccrualAt_C mwStopAccrualAt_C;
        
        private wStopAccrualAt_V mwStopAccrualAt_V;
        
        private wStopAccrualAt_TXT mwStopAccrualAt_TXT;
        
        private wStopAccrualAt_cbo mwStopAccrualAt_cbo;
        
        private wRateTiersBasedOn mwRateTiersBasedOn;
        
        private wNumberOfRateTiers mwNumberOfRateTiers;
        
        private wIntegrationType mwIntegrationType;
        
        private wNumberOfBreakPoints mwNumberOfBreakPoints;
        
        private wFPGrid mwFPGrid;
        
        private wCommonTXT_FPGrid mwCommonTXT_FPGrid;
        
        private wFPGrid_horizontalBar mwFPGrid_horizontalBar;
        
        private wBreakpoint1_C mwBreakpoint1_C;
        
        private wBreakpoint1_V mwBreakpoint1_V;
        
        private wBreakpoint1_TXT mwBreakpoint1_TXT;
        
        private wBreakpoint1_cbo mwBreakpoint1_cbo;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wStandard : WinWindow
    {
        
        public wStandard(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnStandardDefinition";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinRadioButton rdStandard
        {
            get
            {
                if ((this.mrdStandard == null))
                {
                    this.mrdStandard = new WinRadioButton(this);
                    #region Search Criteria
                    this.mrdStandard.SearchProperties[WinRadioButton.PropertyNames.Name] = "Standard";
                    this.mrdStandard.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mrdStandard.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mrdStandard;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mrdStandard;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wCustomCode : WinWindow
    {
        
        public wCustomCode(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "btnCustomCode";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinRadioButton rdCustomCode
        {
            get
            {
                if ((this.mrdCustomCode == null))
                {
                    this.mrdCustomCode = new WinRadioButton(this);
                    #region Search Criteria
                    this.mrdCustomCode.SearchProperties[WinRadioButton.PropertyNames.Name] = "Custom code";
                    this.mrdCustomCode.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mrdCustomCode.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mrdCustomCode;
            }
        }
        #endregion
        
        #region Fields
        private WinRadioButton mrdCustomCode;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wServiceProrateFormula : WinWindow
    {
        
        public wServiceProrateFormula(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "chkServiceProrateFormula";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinCheckBox chkServiceProrateFormula
        {
            get
            {
                if ((this.mchkServiceProrateFormula == null))
                {
                    this.mchkServiceProrateFormula = new WinCheckBox(this);
                    #region Search Criteria
                    this.mchkServiceProrateFormula.SearchProperties[WinCheckBox.PropertyNames.Name] = "Service prorate formula";
                    this.mchkServiceProrateFormula.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mchkServiceProrateFormula.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mchkServiceProrateFormula;
            }
        }
        #endregion
        
        #region Fields
        private WinCheckBox mchkServiceProrateFormula;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wServiceProrateReduction : WinWindow
    {
        
        public wServiceProrateReduction(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboServiceProrateReduction";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinComboBox cboServiceProrateReduction
        {
            get
            {
                if ((this.mcboServiceProrateReduction == null))
                {
                    this.mcboServiceProrateReduction = new WinComboBox(this);
                    #region Search Criteria
                    this.mcboServiceProrateReduction.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mcboServiceProrateReduction.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mcboServiceProrateReduction;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mcboServiceProrateReduction;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wPayAverage : WinWindow
    {
        
        public wPayAverage(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboPayAverage";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinComboBox cboPayAverage
        {
            get
            {
                if ((this.mcboPayAverage == null))
                {
                    this.mcboPayAverage = new WinComboBox(this);
                    #region Search Criteria
                    this.mcboPayAverage.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mcboPayAverage.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mcboPayAverage;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mcboPayAverage;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wService : WinWindow
    {
        
        public wService(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboService";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinComboBox cboService
        {
            get
            {
                if ((this.mcboService == null))
                {
                    this.mcboService = new WinComboBox(this);
                    #region Search Criteria
                    this.mcboService.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mcboService.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mcboService;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mcboService;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wServiceLimitTo : WinWindow
    {
        
        public wServiceLimitTo(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "nudServiceLimit";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public txtServiceLimitTo txtServiceLimitTo
        {
            get
            {
                if ((this.mtxtServiceLimitTo == null))
                {
                    this.mtxtServiceLimitTo = new txtServiceLimitTo(this);
                }
                return this.mtxtServiceLimitTo;
            }
        }
        #endregion
        
        #region Fields
        private txtServiceLimitTo mtxtServiceLimitTo;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class txtServiceLimitTo : WinEdit
    {
        
        public txtServiceLimitTo(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinEdit txt
        {
            get
            {
                if ((this.mtxt == null))
                {
                    this.mtxt = new WinEdit(this);
                    #region Search Criteria
                    this.mtxt.SearchProperties[WinEdit.PropertyNames.Name] = "Text area";
                    this.mtxt.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mtxt;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mtxt;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wStopAccrualAt_C : WinWindow
    {
        
        public wStopAccrualAt_C(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_btnConstant";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinButton btnC
        {
            get
            {
                if ((this.mbtnC == null))
                {
                    this.mbtnC = new WinButton(this);
                    #region Search Criteria
                    this.mbtnC.SearchProperties[WinButton.PropertyNames.Name] = "C";
                    this.mbtnC.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mbtnC.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mbtnC;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mbtnC;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wStopAccrualAt_V : WinWindow
    {
        
        public wStopAccrualAt_V(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_btnVariable";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinButton btnV
        {
            get
            {
                if ((this.mbtnV == null))
                {
                    this.mbtnV = new WinButton(this);
                    #region Search Criteria
                    this.mbtnV.SearchProperties[WinButton.PropertyNames.Name] = "V";
                    this.mbtnV.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mbtnV.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mbtnV;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mbtnV;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wStopAccrualAt_TXT : WinWindow
    {
        
        public wStopAccrualAt_TXT(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_numEditConstant";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public txt txt
        {
            get
            {
                if ((this.mtxt == null))
                {
                    this.mtxt = new txt(this);
                }
                return this.mtxt;
            }
        }
        #endregion
        
        #region Fields
        private txt mtxt;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class txt : WinEdit
    {
        
        public txt(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinEdit UI_numEditConstantEdit1
        {
            get
            {
                if ((this.mUI_numEditConstantEdit1 == null))
                {
                    this.mUI_numEditConstantEdit1 = new WinEdit(this);
                    #region Search Criteria
                    this.mUI_numEditConstantEdit1.SearchProperties[WinEdit.PropertyNames.Name] = "Text area";
                    this.mUI_numEditConstantEdit1.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mUI_numEditConstantEdit1;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUI_numEditConstantEdit1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wStopAccrualAt_cbo : WinWindow
    {
        
        public wStopAccrualAt_cbo(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_cboVariable";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinComboBox cbo
        {
            get
            {
                if ((this.mcbo == null))
                {
                    this.mcbo = new WinComboBox(this);
                    #region Search Criteria
                    this.mcbo.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mcbo.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mcbo;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mcbo;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wRateTiersBasedOn : WinWindow
    {
        
        public wRateTiersBasedOn(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboRateTiersBasis";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinComboBox cboRateTiersBasedOn
        {
            get
            {
                if ((this.mcboRateTiersBasedOn == null))
                {
                    this.mcboRateTiersBasedOn = new WinComboBox(this);
                    #region Search Criteria
                    this.mcboRateTiersBasedOn.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mcboRateTiersBasedOn.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mcboRateTiersBasedOn;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mcboRateTiersBasedOn;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wNumberOfRateTiers : WinWindow
    {
        
        public wNumberOfRateTiers(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "nudNumberOfRateTiers";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public txtNumberOfRateTiers txtNumberOfRateTiers
        {
            get
            {
                if ((this.mtxtNumberOfRateTiers == null))
                {
                    this.mtxtNumberOfRateTiers = new txtNumberOfRateTiers(this);
                }
                return this.mtxtNumberOfRateTiers;
            }
        }
        #endregion
        
        #region Fields
        private txtNumberOfRateTiers mtxtNumberOfRateTiers;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class txtNumberOfRateTiers : WinEdit
    {
        
        public txtNumberOfRateTiers(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinEdit txt
        {
            get
            {
                if ((this.mtxt == null))
                {
                    this.mtxt = new WinEdit(this);
                    #region Search Criteria
                    this.mtxt.SearchProperties[WinEdit.PropertyNames.Name] = "Text area";
                    this.mtxt.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mtxt;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mtxt;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wIntegrationType : WinWindow
    {
        
        public wIntegrationType(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "cboIntegrationType";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinComboBox cboIntegrationType
        {
            get
            {
                if ((this.mcboIntegrationType == null))
                {
                    this.mcboIntegrationType = new WinComboBox(this);
                    #region Search Criteria
                    this.mcboIntegrationType.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mcboIntegrationType.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mcboIntegrationType;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mcboIntegrationType;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wNumberOfBreakPoints : WinWindow
    {
        
        public wNumberOfBreakPoints(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "nudNumberOfBreakPoints";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public txtNumberOfBreakPoints txtNumberOfBreakPoints
        {
            get
            {
                if ((this.mtxtNumberOfBreakPoints == null))
                {
                    this.mtxtNumberOfBreakPoints = new txtNumberOfBreakPoints(this);
                }
                return this.mtxtNumberOfBreakPoints;
            }
        }
        #endregion
        
        #region Fields
        private txtNumberOfBreakPoints mtxtNumberOfBreakPoints;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class txtNumberOfBreakPoints : WinEdit
    {
        
        public txtNumberOfBreakPoints(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinEdit txt
        {
            get
            {
                if ((this.mtxt == null))
                {
                    this.mtxt = new WinEdit(this);
                    #region Search Criteria
                    this.mtxt.SearchProperties[WinEdit.PropertyNames.Name] = "Text area";
                    this.mtxt.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mtxt;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mtxt;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wFPGrid : WinWindow
    {
        
        public wFPGrid(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ControlName, "spr", PropertyExpressionOperator.Contains));
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinClient grid
        {
            get
            {
                if ((this.mgrid == null))
                {
                    this.mgrid = new WinClient(this);
                    #region Search Criteria
                    this.mgrid.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mgrid.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mgrid;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mgrid;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wCommonTXT_FPGrid : WinWindow
    {
        
        public wCommonTXT_FPGrid(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "ctlNumEditor";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinEdit txt
        {
            get
            {
                if ((this.mtxt == null))
                {
                    this.mtxt = new WinEdit(this);
                    #region Search Criteria
                    this.mtxt.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
                    this.mtxt.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mtxt;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mtxt;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wFPGrid_horizontalBar : WinWindow
    {
        
        public wFPGrid_horizontalBar(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties.Add(new PropertyExpression(WinWindow.PropertyNames.ClassName, "WindowsForms10.Window", PropertyExpressionOperator.Contains));
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "18";
            this.SearchConfigurations.Add(SearchConfiguration.AlwaysSearch);
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinClient bar
        {
            get
            {
                if ((this.mbar == null))
                {
                    this.mbar = new WinClient(this);
                    #region Search Criteria
                    this.mbar.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mbar;
            }
        }
        #endregion
        
        #region Fields
        private WinClient mbar;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wBreakpoint1_C : WinWindow
    {
        
        public wBreakpoint1_C(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_btnConstant";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinButton btnC
        {
            get
            {
                if ((this.mbtnC == null))
                {
                    this.mbtnC = new WinButton(this);
                    #region Search Criteria
                    this.mbtnC.SearchProperties[WinButton.PropertyNames.Name] = "C";
                    this.mbtnC.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mbtnC;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mbtnC;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wBreakpoint1_V : WinWindow
    {
        
        public wBreakpoint1_V(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_btnVariable";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinButton btnV
        {
            get
            {
                if ((this.mbtnV == null))
                {
                    this.mbtnV = new WinButton(this);
                    #region Search Criteria
                    this.mbtnV.SearchProperties[WinButton.PropertyNames.Name] = "V";
                    this.mbtnV.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mbtnV;
            }
        }
        #endregion
        
        #region Fields
        private WinButton mbtnV;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wBreakpoint1_TXT : WinWindow
    {
        
        public wBreakpoint1_TXT(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_numEditConstant";
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public txt1 txt
        {
            get
            {
                if ((this.mtxt == null))
                {
                    this.mtxt = new txt1(this);
                }
                return this.mtxt;
            }
        }
        #endregion
        
        #region Fields
        private txt1 mtxt;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class txt1 : WinEdit
    {
        
        public txt1(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinEdit UI_numEditConstantEdit1
        {
            get
            {
                if ((this.mUI_numEditConstantEdit1 == null))
                {
                    this.mUI_numEditConstantEdit1 = new WinEdit(this);
                    #region Search Criteria
                    this.mUI_numEditConstantEdit1.SearchProperties[WinEdit.PropertyNames.Name] = "Text area";
                    this.mUI_numEditConstantEdit1.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mUI_numEditConstantEdit1;
            }
        }
        #endregion
        
        #region Fields
        private WinEdit mUI_numEditConstantEdit1;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "12.0.31101.0")]
    public class wBreakpoint1_cbo : WinWindow
    {
        
        public wBreakpoint1_cbo(UITestControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[WinWindow.PropertyNames.ControlName] = "_cboVariable";
            this.SearchProperties[WinWindow.PropertyNames.Instance] = "2";
            this.WindowTitles.Add("Retirement Studio");
            #endregion
        }
        
        #region Properties
        public WinComboBox cbo
        {
            get
            {
                if ((this.mcbo == null))
                {
                    this.mcbo = new WinComboBox(this);
                    #region Search Criteria
                    this.mcbo.WindowTitles.Add("Retirement Studio");
                    #endregion
                }
                return this.mcbo;
            }
        }
        #endregion
        
        #region Fields
        private WinComboBox mcbo;
        #endregion
    }
}
